language: python
sudo: true
python:
    - "2.7"

install:
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - pip install -r test_requirements.txt

script:
    - ./build.sh

after_success:
    - coveralls
deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file:
    - "dist/linux32/openbazaard-linux32"
  skip_cleanup: true
