language: python
sudo: true
python:
    - "2.7"
services:
  - docker

install:
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - pip install -r test_requirements.txt

script:
  - "docker run -i -v \"${PWD}:/MyProgram\" toopher/ubuntu-i386:centos6 /bin/bash -c \"linux32 --32bit i386 /MyProgram/build.sh\""
    # - ./build.sh

after_success:
    - coveralls
deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file:
    - "dist/linux32/openbazaard-linux32"
  skip_cleanup: true
